In [1]:
#importing pandas library
import pandas as pd

In [10]:
#pd.read_csv("countries_of_the_world.csv", header = None, names = ['Country', 'Region'])
pd.read_csv("countries_of_the_world.csv")
df

             Country                               Region
0       Afghanistan         ASIA (EX. NEAR EAST)
1           Albania   EASTERN EUROPE
2           Algeria   NORTHERN AFRICA
3    American Samoa   OCEANIA
4           Andorra   WESTERN EUROPE
..               ...                                  ...
222       West Bank   NEAR EAST
223  Western Sahara   NORTHERN AFRICA
224           Yemen   NEAR EAST
225          Zambia   SUB-SAHARAN AFRICA
226        Zimbabwe   SUB-SAHARAN AFRICA

[227 rows x 2 columns]

# for reading txt file using read_csv method

In [11]:
df1 = pd.read_csv("countries_of_the_world.txt", sep = '\t') #sep to seperate the markers alphabets
df1

             Country                               Region
0       Afghanistan         ASIA (EX. NEAR EAST)
1           Albania   EASTERN EUROPE
2           Algeria   NORTHERN AFRICA
3    American Samoa   OCEANIA
4           Andorra   WESTERN EUROPE
..               ...                                  ...
222       West Bank   NEAR EAST
223  Western Sahara   NORTHERN AFRICA
224           Yemen   NEAR EAST
225          Zambia   SUB-SAHARAN AFRICA
226        Zimbabwe   SUB-SAHARAN AFRICA

[227 rows x 2 columns]

# for reading txt file using read_table method

In [13]:
df1 = pd.read_table("countries_of_the_world.txt")
df1
#read table works well with txt but not with csv files

             Country                               Region
0       Afghanistan         ASIA (EX. NEAR EAST)
1           Albania   EASTERN EUROPE
2           Algeria   NORTHERN AFRICA
3    American Samoa   OCEANIA
4           Andorra   WESTERN EUROPE
..               ...                                  ...
222       West Bank   NEAR EAST
223  Western Sahara   NORTHERN AFRICA
224           Yemen   NEAR EAST
225          Zambia   SUB-SAHARAN AFRICA
226        Zimbabwe   SUB-SAHARAN AFRICA

[227 rows x 2 columns]

# for using json files

In [21]:
df3 = pd.read_json("json_sample.json")
df3

,12 Strong,A Fantastic Woman (Una Mujer Fantástica),All The Money In The World,Bilal: A New Breed Of Hero,Call Me By Your Name,Darkest Hour,Den Of Thieves,Ferdinand,Fifty Shades Freed,Film Stars Don'T Die In Liverpool,Forever My Girl,Golden Exits,Hostiles,"I, Tonya",Insidious: The Last Key,Jumanji: Welcome To The Jungle,Mary And The Witch'S Flower,Maze Runner: The Death Cure,Molly'S Game,Paddington 2,Padmaavat,Permission,Peter Rabbit,Phantom Thread,Pitch Perfect 3,Proud Mary,Sanpo Suru Shinryakusha,Star Wars: The Last Jedi,The 15:17 To Paris,The Commuter,The Disaster Artist,The Greatest Showman,The Insult (L'Insulte),The Post,The Shape Of Water,"Three Billboards Outside Ebbing, Missouri",Till The End Of The World,Winchester
0,"{'Genre': 'Action', 'Gross': '$453,173', 'IMDB...","{'popcornscore': 83, 'rating': 'R', 'tomatosco...","{'popcornscore': 71, 'rating': 'R', 'tomatosco...","{'popcornscore': 91, 'rating': 'PG13', 'tomato...","{'popcornscore': 87, 'rating': 'R', 'tomatosco...","{'popcornscore': 84, 'rating': 'PG13', 'tomato...","{'Genre': 'Action', 'Gross': '$491,898', 'IMDB...","{'popcornscore': 49, 'rating': 'PG', 'tomatosc...","{'Genre': 'Drama', 'Gross': 'unknown', 'IMDB M...","{'popcornscore': 69, 'rating': 'R', 'tomatosco...","{'popcornscore': 91, 'rating': 'PG', 'tomatosc...","{'Genre': 'Drama', 'Gross': 'unknown', 'IMDB M...","{'Genre': 'Adventure', 'Gross': '$548,886', 'I...","{'popcornscore': 89, 'rating': 'R', 'tomatosco...","{'popcornscore': 51, 'rating': 'PG13', 'tomato...","{'Genre': 'Action', 'Gross': '$760,867', 'IMDB...","{'popcornscore': 78, 'rating': 'PG', 'tomatosc...","{'Genre': 'Action', 'Gross': '$720,463', 'IMDB...","{'popcornscore': 85, 'rating': 'R', 'tomatosco...","{'Genre': 'Animation', 'Gross': '$184,414', 'I...","{'popcornscore': 62, 'rating': 'NR', 'tomatosc...","{'Genre': 'Comedy', 'Gross': 'unknown', 'IMDB ...","{'Genre': 'Animation', 'Gross': 'unknown', 'IM...","{'popcornscore': 68, 'rating': 'R', 'tomatosco...","{'popcornscore': 52, 'rating': 'PG13', 'tomato...","{'popcornscore': 56, 'rating': 'R', 'tomatosco...","{'Genre': 'Drama', 'Gross': 'unknown', 'IMDB M...","{'popcornscore': 48, 'rating': 'PG13', 'tomato...","{'Genre': 'Drama', 'Gross': 'unknown', 'IMDB M...","{'popcornscore': 48, 'rating': 'PG13', 'tomato...","{'popcornscore': 89, 'rating': 'R', 'tomatosco...","{'Genre': 'Biography', 'Gross': '$627,248', 'I...","{'popcornscore': 86, 'rating': 'R', 'tomatosco...","{'Genre': 'Biography', 'Gross': '$463,228', 'I...","{'Genre': 'Adventure', 'Gross': '$448,287', 'I...","{'popcornscore': 87, 'rating': 'R', 'tomatosco...","{'popcornscore': -1, 'rating': 'NR', 'tomatosc...","{'Genre': 'Biography', 'Gross': '$696,786', 'I..."

# excel files

In [19]:
df4 = pd.read_excel("world_population_excel_workbook.xlsx", sheet_name = 'Sheet1')
df4

     Rank CCA3                           Country              Capital
0      36  AFG                       Afghanistan                Kabul
1     138  ALB                           Albania               Tirana
2      34  DZA                           Algeria              Algiers
3     213  ASM                    American Samoa            Pago Pago
4     203  AND                           Andorra     Andorra la Vella
5      42  AGO                            Angola               Luanda
6     224  AIA                          Anguilla           The Valley
7     201  ATG               Antigua and Barbuda       Saint Johnâ€™s
8      33  ARG                         Argentina         Buenos Aires
9     140  ARM                           Armenia              Yerevan
10    198  ABW                             Aruba           Oranjestad
11     55  AUS                         Australia             Canberra
12     99  AUT                           Austria               Vienna
13     91  AZE                        Azerbaijan                 Baku
14    176  BHS                           Bahamas               Nassau
15    154  BHR                           Bahrain               Manama
16      8  BGD                        Bangladesh                Dhaka
17    186  BRB                          Barbados           Bridgetown
18     96  BLR                           Belarus                Minsk
19     81  BEL                           Belgium             Brussels
20    177  BLZ                            Belize             Belmopan
21     77  BEN                             Benin           Porto-Novo
22    206  BMU                           Bermuda             Hamilton
23    165  BTN                            Bhutan              Thimphu
24     80  BOL                           Bolivia                Sucre
25    137  BIH            Bosnia and Herzegovina             Sarajevo
26    144  BWA                          Botswana             Gaborone
27      7  BRA                            Brazil             Brasilia
28    221  VGB            British Virgin Islands            Road Town
29    175  BRN                            Brunei  Bandar Seri Begawan
30    108  BGR                          Bulgaria                Sofia
31     58  BFA                      Burkina Faso          Ouagadougou
32     78  BDI                           Burundi            Bujumbura
33     73  KHM                          Cambodia           Phnom Penh
34     53  CMR                          Cameroon              Yaounde
35     39  CAN                            Canada               Ottawa
36    171  CPV                        Cape Verde                Praia
37    205  CYM                    Cayman Islands          George Town
38    117  CAF          Central African Republic               Bangui
39     69  TCD                              Chad            N'Djamena
40     65  CHL                             Chile             Santiago
41      1  CHN                             China              Beijing
42     28  COL                          Colombia               Bogota
43    163  COM                           Comoros               Moroni
44    223  COK                      Cook Islands               Avarua
45    124  CRI                        Costa Rica            San JosÃ©
46    130  HRV                           Croatia               Zagreb
47     85  CUB                              Cuba               Havana
48    189  CUW                           Curacao           Willemstad
49    158  CYP                            Cyprus              Nicosia
50     88  CZE                    Czech Republic               Prague
51    115  DNK                           Denmark           Copenhagen
52    160  DJI                          Djibouti             Djibouti
53    204  DMA                          Dominica               Roseau
54     84  DOM                Dominican Republic        Santo Domingo
55     15  COD                          DR Congo             Kinshasa
56     67  ECU                           Ecuador                Quito
57     14  EGY                             Egypt                Cairo
58    112  SLV                       El Salvador         San Salvador
59    152  GNQ                 Equatorial Guinea               Malabo
60    132  ERI                           Eritrea               Asmara
61    156  EST                           Estonia              Tallinn
62    159  SWZ                          Eswatini              Mbabane
63     12  ETH                          Ethiopia          Addis Ababa
64    231  FLK                  Falkland Islands              Stanley
65    209  FRO                     Faroe Islands            TÃ³rshavn
66    162  FJI                              Fiji                 Suva
67    118  FIN                           Finland             Helsinki
68     23  FRA                            France                Paris
69    184  GUF                     French Guiana              Cayenne
70    183  PYF                  French Polynesia              Papeete
71    146  GAB                             Gabon           Libreville
72    142  GMB                            Gambia               Banjul
73    131  GEO                           Georgia              Tbilisi
74     19  DEU                           Germany               Berlin
75     47  GHA                             Ghana                Accra
76    219  GIB                         Gibraltar            Gibraltar
77     90  GRC                            Greece               Athens
78    208  GRL                         Greenland                 Nuuk
79    193  GRD                           Grenada       Saint George's
80    178  GLP                        Guadeloupe          Basse-Terre
81    191  GUM                              Guam            HagÃ¥tÃ±a
82     68  GTM                         Guatemala       Guatemala City
83    207  GGY                          Guernsey     Saint Peter Port
84     75  GIN                            Guinea              Conakry
85    149  GNB                     Guinea-Bissau               Bissau
86    164  GUY                            Guyana           Georgetown
87     82  HTI                             Haiti       Port-au-Prince
88     89  HND                          Honduras          Tegucigalpa
89    104  HKG                         Hong Kong            Hong Kong
90     94  HUN                           Hungary             Budapest
91    179  ISL                           Iceland           ReykjavÃ­k
92      2  IND                             India            New Delhi
93      4  IDN                         Indonesia              Jakarta
94     17  IRN                              Iran               Tehran
95     35  IRQ                              Iraq              Baghdad
96    125  IRL                           Ireland               Dublin
97    202  IMN                       Isle of Man              Douglas
98     98  ISR                            Israel            Jerusalem
99     25  ITA                             Italy                 Rome
100    52  CIV                       Ivory Coast         Yamoussoukro
101   139  JAM                           Jamaica             Kingston
102    11  JPN                             Japan                Tokyo
103   195  JEY                            Jersey         Saint Helier
104    83  JOR                            Jordan                Amman
105    66  KAZ                        Kazakhstan            Nursultan
106    27  KEN                             Kenya              Nairobi
107   192  KIR                          Kiribati               Tarawa
108   129  KWT                            Kuwait          Kuwait City
109   110  KGZ                        Kyrgyzstan              Bishkek
110   103  LAO                              Laos            Vientiane
111   151  LVA                            Latvia                 Riga
112   119  LBN                           Lebanon               Beirut
113   147  LSO                           Lesotho               Maseru
114   121  LBR                           Liberia             Monrovia
115   107  LBY                             Libya              Tripoli
116   216  LIE                     Liechtenstein                Vaduz
117   141  LTU                         Lithuania              Vilnius
118   168  LUX                        Luxembourg           Luxembourg
119   167  MAC                             Macau    Concelho de Macau
120    50  MDG                        Madagascar         Antananarivo
121    62  MWI                            Malawi             Lilongwe
122    45  MYS                          Malaysia         Kuala Lumpur
123   174  MDV                          Maldives                MalÃ©
124    59  MLI                              Mali               Bamako
125   173  MLT                             Malta             Valletta
126   215  MHL                  Marshall Islands               Majuro
127   180  MTQ                        Martinique       Fort-de-France
128   126  MRT                        Mauritania           Nouakchott
129   157  MUS                         Mauritius           Port Louis
130   182  MYT                           Mayotte            Mamoudzou
131    10  MEX                            Mexico          Mexico City
132   194  FSM                        Micronesia              Palikir
133   135  MDA                           Moldova             Chisinau
134   217  MCO                            Monaco               Monaco
135   134  MNG                          Mongolia          Ulaanbaatar
136   169  MNE                        Montenegro            Podgorica
137   230  MSR                        Montserrat               Brades
138    40  MAR                           Morocco                Rabat
139    48  MOZ                        Mozambique               Maputo
140    26  MMR                           Myanmar          Nay Pyi Taw
141   145  NAM                           Namibia             Windhoek
142   225  NRU                             Nauru                Yaren
143    49  NPL                             Nepal            Kathmandu
144    71  NLD                       Netherlands            Amsterdam
145   185  NCL                     New Caledonia              NoumÃ©a
146   123  NZL                       New Zealand           Wellington
147   106  NIC                         Nicaragua              Managua
148    54  NER                             Niger               Niamey
149     6  NGA                           Nigeria                Abuja
150   232  NIU                              Niue                Alofi
151    56  PRK                       North Korea            Pyongyang
152   150  MKD                   North Macedonia               Skopje
153   210  NFK          Northern Mariana Islands               Saipan
154   120  NOR                            Norway                 Oslo
155   127  OMN                              Oman               Muscat
156     5  PAK                          Pakistan            Islamabad
157   222  PLW                             Palau            Ngerulmud
158   122  PSE                         Palestine             Ramallah
159   128  PAN                            Panama          Panama City
160    93  PNG                  Papua New Guinea         Port Moresby
161   109  PRY                          Paraguay            AsunciÃ³n
162    44  PER                              Peru                 Lima
163    13  PHL                       Philippines               Manila
164    37  POL                            Poland               Warsaw
165    92  PRT                          Portugal               Lisbon
166   136  PRI                       Puerto Rico             San Juan
167   143  QAT                             Qatar                 Doha
168   114  COG             Republic of the Congo          Brazzaville
169   161  REU                           Reunion          Saint-Denis
170    64  ROU                           Romania            Bucharest
171     9  RUS                            Russia               Moscow
172    76  RWA                            Rwanda               Kigali
173   228  BLM                  Saint Barthelemy             Gustavia
174   211  KNA             Saint Kitts and Nevis           Basseterre
175   190  LCA                       Saint Lucia             Castries
176   220  MAF                      Saint Martin              Marigot
177   229  SPM         Saint Pierre and Miquelon         Saint-Pierre
178   199  VCT  Saint Vincent and the Grenadines            Kingstown
179   188  WSM                             Samoa                 Apia
180   218  SMR                        San Marino           San Marino
181   187  STP             Sao Tome and Principe           SÃ£o TomÃ©
182    41  SAU                      Saudi Arabia               Riyadh
183    72  SEN                           Senegal                Dakar
184   105  SRB                            Serbia             Belgrade
185   196  SYC                        Seychelles             Victoria
186   102  SLE                      Sierra Leone             Freetown
187   113  SGP                         Singapore            Singapore
188   214  SXM                      Sint Maarten          Philipsburg
189   116  SVK                          Slovakia           Bratislava
190   148  SVN                          Slovenia            Ljubljana
191   166  SLB                   Solomon Islands              Honiara
192    70  SOM                           Somalia            Mogadishu
193    24  ZAF                      South Africa             Pretoria
194    29  KOR                       South Korea                Seoul
195    86  SSD                       South Sudan                 Juba
196    30  ESP                             Spain               Madrid
197    61  LKA                         Sri Lanka              Colombo
198    32  SDN                             Sudan             Khartoum
199   170  SUR                          Suriname           Paramaribo
200    87  SWE                            Sweden            Stockholm
201   101  CHE                       Switzerland                 Bern
202    60  SYR                             Syria             Damascus
203    57  TWN                            Taiwan               Taipei
204    95  TJK                        Tajikistan             Dushanbe
205    22  TZA                          Tanzania               Dodoma
206    20  THA                          Thailand              Bangkok
207   155  TLS                       Timor-Leste                 Dili
208   100  TGO                              Togo                LomÃ©
209   233  TKL                           Tokelau             Nukunonu
210   197  TON                             Tonga         Nukuâ€˜alofa
211   153  TTO               Trinidad and Tobago        Port-of-Spain
212    79  TUN                           Tunisia                Tunis
213    18  TUR                            Turkey               Ankara
214   111  TKM                      Turkmenistan             Ashgabat
215   212  TCA          Turks and Caicos Islands        Cockburn Town
216   227  TUV                            Tuvalu             Funafuti
217    31  UGA                            Uganda              Kampala
218    38  UKR                           Ukraine                 Kiev
219    97  ARE              United Arab Emirates            Abu Dhabi
220    21  GBR                    United Kingdom               London
221     3  USA                     United States     Washington, D.C.
222   200  VIR      United States Virgin Islands     Charlotte Amalie
223   133  URY                           Uruguay           Montevideo
224    43  UZB                        Uzbekistan             Tashkent
225   181  VUT                           Vanuatu            Port-Vila
226   234  VAT                      Vatican City         Vatican City
227    51  VEN                         Venezuela              Caracas
228    16  VNM                           Vietnam                Hanoi
229   226  WLF                 Wallis and Futuna             Mata-Utu
230   172  ESH                    Western Sahara            El AaiÃºn
231    46  YEM                             Yemen                Sanaa
232    63  ZMB                            Zambia               Lusaka
233    74  ZWE                          Zimbabwe               Harare

In [18]:
pd.set_option('display.max.rows', 235)

In [20]:
pd.set_option('display.max.columns', 40)

In [22]:
#reviewing excel files
df4.info()
#gives a basic info about the dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rank     234 non-null    int64
 1   CCA3     234 non-null    object
 2   Country  234 non-null    object
 3   Capital  234 non-null    object
dtypes: int64(1), object(3)
memory usage: 7.4+ KB

In [24]:
df4.shape
#shape of the data frame

(234, 4)

In [25]:
df4.head(10) #for first 10 rows

   Rank CCA3              Country           Capital
0    36  AFG          Afghanistan             Kabul
1   138  ALB              Albania            Tirana
2    34  DZA              Algeria           Algiers
3   213  ASM       American Samoa         Pago Pago
4   203  AND              Andorra  Andorra la Vella
5    42  AGO               Angola            Luanda
6   224  AIA             Anguilla        The Valley
7   201  ATG  Antigua and Barbuda    Saint Johnâ€™s
8    33  ARG            Argentina      Buenos Aires
9   140  ARM              Armenia           Yerevan

In [26]:
#last 10 rows
df4.tail(10)

     Rank CCA3            Country       Capital
224    43  UZB         Uzbekistan      Tashkent
225   181  VUT            Vanuatu     Port-Vila
226   234  VAT       Vatican City  Vatican City
227    51  VEN          Venezuela       Caracas
228    16  VNM            Vietnam         Hanoi
229   226  WLF  Wallis and Futuna      Mata-Utu
230   172  ESH     Western Sahara     El AaiÃºn
231    46  YEM              Yemen         Sanaa
232    63  ZMB             Zambia        Lusaka
233    74  ZWE           Zimbabwe        Harare

In [35]:
#to see only one column
df4['CCA3']

0      AFG
1      ALB
2      DZA
3      ASM
4      AND
5      AGO
6      AIA
7      ATG
8      ARG
9      ARM
10     ABW
11     AUS
12     AUT
13     AZE
14     BHS
15     BHR
16     BGD
17     BRB
18     BLR
19     BEL
20     BLZ
21     BEN
22     BMU
23     BTN
24     BOL
25     BIH
26     BWA
27     BRA
28     VGB
29     BRN
30     BGR
31     BFA
32     BDI
33     KHM
34     CMR
35     CAN
36     CPV
37     CYM
38     CAF
39     TCD
40     CHL
41     CHN
42     COL
43     COM
44     COK
45     CRI
46     HRV
47     CUB
48     CUW
49     CYP
50     CZE
51     DNK
52     DJI
53     DMA
54     DOM
55     COD
56     ECU
57     EGY
58     SLV
59     GNQ
60     ERI
61     EST
62     SWZ
63     ETH
64     FLK
65     FRO
66     FJI
67     FIN
68     FRA
69     GUF
70     PYF
71     GAB
72     GMB
73     GEO
74     DEU
75     GHA
76     GIB
77     GRC
78     GRL
79     GRD
80     GLP
81     GUM
82     GTM
83     GGY
84     GIN
85     GNB
86     GUY
87     HTI
88     HND
89     HKG
90     HUN
91     ISL
92     IND
93     IDN
94     IRN
95     IRQ
96     IRL
97     IMN
98     ISR
99     ITA
100    CIV
101    JAM
102    JPN
103    JEY
104    JOR
105    KAZ
106    KEN
107    KIR
108    KWT
109    KGZ
110    LAO
111    LVA
112    LBN
113    LSO
114    LBR
115    LBY
116    LIE
117    LTU
118    LUX
119    MAC
120    MDG
121    MWI
122    MYS
123    MDV
124    MLI
125    MLT
126    MHL
127    MTQ
128    MRT
129    MUS
130    MYT
131    MEX
132    FSM
133    MDA
134    MCO
135    MNG
136    MNE
137    MSR
138    MAR
139    MOZ
140    MMR
141    NAM
142    NRU
143    NPL
144    NLD
145    NCL
146    NZL
147    NIC
148    NER
149    NGA
150    NIU
151    PRK
152    MKD
153    NFK
154    NOR
155    OMN
156    PAK
157    PLW
158    PSE
159    PAN
160    PNG
161    PRY
162    PER
163    PHL
164    POL
165    PRT
166    PRI
167    QAT
168    COG
169    REU
170    ROU
171    RUS
172    RWA
173    BLM
174    KNA
175    LCA
176    MAF
177    SPM
178    VCT
179    WSM
180    SMR
181    STP
182    SAU
183    SEN
184    SRB
185    SYC
186    SLE
187    SGP
188    SXM
189    SVK
190    SVN
191    SLB
192    SOM
193    ZAF
194    KOR
195    SSD
196    ESP
197    LKA
198    SDN
199    SUR
200    SWE
201    CHE
202    SYR
203    TWN
204    TJK
205    TZA
206    THA
207    TLS
208    TGO
209    TKL
210    TON
211    TTO
212    TUN
213    TUR
214    TKM
215    TCA
216    TUV
217    UGA
218    UKR
219    ARE
220    GBR
221    USA
222    VIR
223    URY
224    UZB
225    VUT
226    VAT
227    VEN
228    VNM
229    WLF
230    ESH
231    YEM
232    ZMB
233    ZWE
Name: CCA3, dtype: object

In [38]:
#to check for specific details about a particular row
df4.iloc[224]

Rank               43
CCA3              UZB
Country    Uzbekistan
Capital      Tashkent
Name: 224, dtype: object

In [41]:
df4.loc['Uzbekistan']

KeyError: 'Uzbekistan'